In [ ]:
%pip install kagglehub # SIRVE PARA DESCARGAR DATASETS DE KAGGLE

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.18-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /Users/chrisjr/Library/Python/3.13/lib/python/site-packages (from kagglehub) (25.0)
Collecting pyyaml (from kagglehub)
  Downloading pyyaml-6.0.3-cp313-cp313-macosx_10_13_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kagglehub) (2.32.4)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (2026.2.25)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.18-py3-none-any.whl (201 kB)
Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl (429 kB)
Downloading pyyaml-6.0.3-cp313-cp313-macosx_10_13_x86_64.whl (181 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, pyyaml, protobuf, kagglesdk, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [kagglehub]/5 [kagglehub]
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.18 protobuf-7.34.1 pyyaml-6.0.3 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

In [9]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Es clave
%pip install ijson # SIRVE PARA LEER ARCHIVOS JSON MUY GRANDES, COMO LOS DE KAGGLE, SIN CARGAR TODO EN MEMORIA

Collecting ijson
  Downloading ijson-3.5.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (23 kB)
Downloading ijson-3.5.0-cp313-cp313-macosx_10_13_x86_64.whl (60 kB)
Installing collected packages: ijson
Successfully installed ijson-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [10]:
# IMPORTAMOS LAS LIBRERIAS PARA LEER LOS ARCHIVOS JSON
import ijson

In [11]:
import kagglehub

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("Cornell-University/arxiv") # DESCARGA EL DATASET DE KAGGLE Y DEVUELVE LA RUTA DONDE SE HA GUARDADO

print("Path to dataset files:", path)

Downloading to /home/kique/.cache/kagglehub/datasets/Cornell-University/arxiv/282.archive...

  8%|███▎                                   | 140M/1.61G [00:27<05:00, 5.27MB/s]

KeyboardInterrupt:

In [12]:
jsonpath = "/home/kique/.cache/kagglehub/datasets/Cornell-University/arxiv/versions/280/"
#jsonpath = "/Users/chrisjr/.cache/kagglehub/datasets/Cornell-University/arxiv/versions/281"

In [13]:
# EL SIGUIENTE CODIGO LEE EL ARCHIVO JSON DE FORMA ITERATIVA, SIN CARGAR TODO EN MEMORIA, Y GUARDA LOS RESUMENES DE LOS ARTICULOS EN UNA LISTA LLAMADA "corpus"

corpus = []

with open(jsonpath+"/arxiv-metadata-oai-snapshot.json", "r") as f: # ABRE EL ARCHIVO JSON PARA LEERLO
    parser = ijson.items(f, '', multiple_values=True) # CREA UN PARSER PARA LEER EL ARCHIVO JSON DE FORMA ITERATIVA, SIN CARGAR TODO EN MEMORIA
    c = 0
    for obj in parser:
        c+=1
        corpus.append(obj["abstract"])
        if c>100:
            break

In [14]:
# CÓDIGO PARA TAMBIÉN OBTENER EL AÑO DE PUBLICACIÓN DE LOS ARTÍCULOS
corpus = []

with open(jsonpath+"/arxiv-metadata-oai-snapshot.json", "r") as f: # ABRE EL ARCHIVO JSON PARA LEERLO
    parser = ijson.items(f, '', multiple_values=True) # CREA UN PARSER PARA LEER EL ARCHIVO JSON DE FORMA ITERATIVA, SIN CARGAR TODO EN MEMORIA
    c = 0
    for obj in parser:
        c+=1
        year = int(obj["update_date"][:4])
        corpus.append({
            "abstract": obj["abstract"],
            "year": year,
            "category": obj["categories"].split()[0] # OBTENEMOS LA PRIMERA CATEGORÍA DE CADA ARTÍCULO
        })
        if c>100:
            break

In [15]:
df_datos = pd.DataFrame(corpus) # CREAMOS UN DATAFRAME DE PANDAS A PARTIR DE LA LISTA DE RESUMENES Y AÑOS
df_datos.head(20) # MOSTRAMOS LAS PRIMERAS FILAS DEL DATAFRAME PARA VER SU ESTRUCTURA

                                             abstract  year           category
0     A fully differential calculation in perturba...  2008             hep-ph
1     We describe a new algorithm, the $(k,\ell)$-...  2008            math.CO
2     The evolution of Earth-Moon system is descri...  2008     physics.gen-ph
3     We show that a determinant of Stirling cycle...  2007            math.CO
4     In this paper we show how to compute the $\L...  2013            math.CA
5     We study the two-particle wave function of p...  2015  cond-mat.mes-hall
6     A rather non-standard quantum representation...  2008              gr-qc
7     A general formulation was developed to repre...  2009  cond-mat.mtrl-sci
8     We discuss the results from the combined IRA...  2010           astro-ph
9     Partial cubes are isometric subgraphs of hyp...  2007            math.CO
10    In this paper we present an algorithm for co...  2008            math.NT
11    Recently, Bruinier and Ono classified cusp f...  2007            math.NT
12    Serre obtained the p-adic limit of the integ...  2008            math.NT
13    In this article we discuss a relation betwee...  2009            math.CA
14    The pure spinor formulation of the ten-dimen...  2009             hep-th
15    In this work, we evaluate the lifetimes of t...  2008             hep-ph
16    Results from spectroscopic observations of t...  2009           astro-ph
17    We give a prescription for how to compute th...  2007             hep-th
18    In this note we give a new method for gettin...  2007            math.PR
19    The shape of the hadronic form factor f+(q2)...  2015             hep-ex

In [16]:
from sklearn.feature_extraction.text import CountVectorizer as CV # IMPORTAMOS LA CLASE CountVectorizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS # IMPORTAMOS LAS PALABRAS VACIAS EN INGLES

In [17]:
contador = CV(stop_words=list(ENGLISH_STOP_WORDS)) # CREAMOS UN OBJETO DE LA CLASE CountVectorizer, PASANDOLE LAS PALABRAS VACIAS EN INGLES PARA QUE LAS ELIMINE DEL CONTADOR DE PALABRAS

In [18]:
X = contador.fit_transform(df_datos["abstract"]) # APLICAMOS EL CONTADOR DE PALABRAS A LA LISTA DE RESUMENES, LO QUE NOS DEVUELVE UNA MATRIZ DE PALABRAS POR DOCUMENTO, DONDE CADA FILA ES UN DOCUMENTO Y CADA COLUMNA ES UNA PALABRA, Y EL VALOR DE CADA CELDA ES EL NUMERO DE VECES QUE ESA PALABRA APARECE EN ESE DOCUMENTO

In [19]:
contador.get_feature_names_out() # NOS DEVUELVE UNA LISTA CON LAS PALABRAS QUE HAN SIDO CONTADAS, ES DECIR, LAS PALABRAS QUE APARECEN EN LOS RESUMENES Y QUE NO SON PALABRAS VACIAS EN INGLES

array(['000010', '001', '0014', ..., 'zero', 'zhan', 'zimmermann'],
      shape=(2730,), dtype=object)

In [20]:
vocabulario = contador.get_feature_names_out()

In [21]:
df = pd.DataFrame(X.toarray(),columns=vocabulario) # CREAMOS UN DATAFRAME DE PANDAS A PARTIR DE LA MATRIZ DE PALABRAS POR DOCUMENTO, PASANDOLE LOS NOMBRES DE LAS COLUMNAS QUE SON LAS PALABRAS CONTADAS
df

,000010,001,0014,005,006,007,010,012,013,021,...,yield,yndur,young,yso,zakrzewski,zariski,zds,zero,zhan,zimmermann
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer # IMPORTAMOS LA CLASE TfidfVectorizer, QUE ES SIMILAR A CountVectorizer PERO EN LUGAR DE CONTAR LAS PALABRAS, CALCULA EL TF-IDF DE CADA PALABRA EN CADA DOCUMENTO, LO QUE NOS DA UNA MEDIDA DE LA IMPORTANCIA DE CADA PALABRA EN CADA DOCUMENTO

In [23]:
vectorizer = TfidfVectorizer(stop_words='english') # CREAMOS UN OBJETO DE LA CLASE TfidfVectorizer, PASANDOLE LAS PALABRAS VACIAS EN INGLES PARA QUE LAS ELIMINE DEL CONTADOR DE PALABRAS, Y QUE CALCULE EL TF-IDF DE CADA PALABRA EN CADA DOCUMENTO
X = vectorizer.fit_transform(df_datos["abstract"]) # APLICAMOS EL CONTADOR DE PALABRAS A LA LISTA DE RESUMENES, LO QUE NOS DEVUELVE UNA MATRIZ DE PALABRAS POR DOCUMENTO, DONDE CADA FILA ES UN DOCUMENTO Y CADA COLUMNA ES UNA PALABRA, Y EL VALOR DE CADA CELDA ES EL TF-IDF DE ESA PALABRA EN ESE DOCUMENTO

In [24]:
X.shape

(101, 2730)

In [25]:
%pip install nltk # SIRVE PARA PROCESAR EL TEXTO, COMO ELIMINAR PALABRAS VACIAS, HACER STEMMING, ETC.

Requirement already satisfied: nltk in /home/kique/anaconda3/lib/python3.13/site-packages (3.9.1)
Requirement already satisfied: click in /home/kique/anaconda3/lib/python3.13/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /home/kique/anaconda3/lib/python3.13/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /home/kique/anaconda3/lib/python3.13/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /home/kique/anaconda3/lib/python3.13/site-packages (from nltk) (4.67.1)
Note: you may need to restart the kernel to use updated packages.

In [26]:
import nltk

# nltk.download('sentiwordnet') # SIRVE PARA OBTENER LA POLARIDAD DE LAS PALABRAS, ES DECIR, SI SON POSITIVAS, NEGATIVAS O NEUTRAS, LO QUE NOS PUEDE AYUDAR A ANALIZAR EL SENTIMIENTO DE LOS RESUMENES DE LOS ARTICULOS
# nltk.download('wordnet') #FALTO AGREGAR  # SIRVE PARA OBTENER LOS SINONIMOS DE LAS PALABRAS, LO QUE NOS PUEDE AYUDAR A ANALIZAR EL CONTENIDO DE LOS RESUMENES DE LOS ARTICULOS

In [27]:
from nltk.corpus import sentiwordnet as swn # 

from nltk.corpus import wordnet as wn

# ESTA FUNCION RECIBE UNA PALABRA Y DEVUELVE SU SENTIMIENTO, QUE ES LA DIFERENCIA ENTRE SU PUNTUACION POSITIVA Y SU PUNTUACION NEGATIVA EN SentiWordNet. SI LA PALABRA NO TIENE UN SYNSET EN WordNet, DEVUELVE 0.
def sentimiento_palabra(palabra):
    synsets = wn.synsets(palabra)
    if not synsets:
        return 0
    
    swn_syn = swn.senti_synset(synsets[0].name())
    return swn_syn.pos_score() - swn_syn.neg_score()

sentimientos = {p: sentimiento_palabra(p) for p in df.columns}

In [28]:
sentimientos

{'000010': 0,
 '001': 0,
 '0014': 0,
 '005': 0,
 '006': 0,
 '007': 0,
 '010': 0,
 '012': 0,
 '013': 0,
 '021': 0,
 '0351': 0,
 '04': 0,
 '05': 0,
 '07': 0,
 '0701050': 0,
 '10': 0.0,
 '100': 0.0,
 '1000': 0.0,
 '12': 0.0,
 '124': 0,
 '13': 0.0,
 '14': 0.0,
 '15': 0.0,
 '150': 0.0,
 '160': 0.0,
 '167': 0,
 '1968': 0,
 '1971': 0,
 '1974': 0,
 '1990': 0,
 '1991': 0,
 '1999': 0,
 '1d': 0,
 '2000': 0,
 '2001': 0,
 '2002': 0,
 '2004': 0,
 '2005': 0,
 '2006': 0,
 '2007': 0,
 '205': 0,
 '22': 0.0,
 '230736': 0,
 '235': 0,
 '246401': 0,
 '248': 0,
 '259000': 0,
 '260': 0,
 '28': 0.0,
 '2d': 0.0,
 '2mass': 0,
 '2n': 0,
 '30': 0.0,
 '3000km': 0,
 '38': 0.0,
 '39': 0.0,
 '3p_0': 0,
 '40': 0.0,
 '4200km': 0,
 '4500': 0,
 '4500km': 0,
 '4d': 0,
 '4n': 0,
 '50': 0.0,
 '500': 0.0,
 '5000': 0,
 '51': 0.0,
 '54': 0.0,
 '5400km': 0,
 '600': 0,
 '61': 0.0,
 '64': 0.0,
 '65': 0.0,
 '72256': 0,
 '727': 0,
 '75': 0.0,
 '7500': 0,
 '7622': 0,
 '76ge': 0,
 '77': 0.0,
 '7x': 0,
 '85': 0.0,
 '90': 0.0,
 '92': 0.0,
 '927': 0,
 'a_f': 0,
 'abelian': 0,
 'ability': 0.5,
 'able': 0.125,
 'absorption': 0.0,
 'abstract': 0.0,
 'accelerable': 0,
 'accelerating': 0.0,
 'acceleration': 0.0,
 'accelerator': 0.0,
 'access': 0.0,
 'according': 0.0,
 'account': 0.0,
 'accounted': 0.0,
 'accreting': 0.0,
 'accretion': 0.0,
 'accuracy': 0.5,
 'accurate': 0.5,
 'accurately': 0.0,
 'achieved': 0.0,
 'acoustic': 0.0,
 'acquired': 0.125,
 'acting': 0.0,
 'action': 0.0,
 'activated': 0.0,
 'active': 0.375,
 'actively': 0.5,
 'actually': 0.375,
 'acyclic': 0.125,
 'adaptation': 0.0,
 'adapted': 0.25,
 'adaptive': 0.25,
 'addition': 0.0,
 'additional': 0.0,
 'additionally': 0.0,
 'additive': 0.0,
 'adequate': 0.0,
 'adiabatic': -0.625,
 'adic': 0,
 'adjoint': 0,
 'admissible': -0.375,
 'admitted': 0.125,
 'adopts': 0.0,
 'adsorption': 0.0,
 'adstatic': 0,
 'advances': 0.0,
 'advantage': 0.625,
 'ae': 0,
 'affect': 0.0,
 'affirmatively': 0.25,
 'aggregation': 0.0,
 'ago': 0.0,
 'agreement': 0.0,
 'agrees': 0.0,
 'aharonov': 0,
 'ahler': 0,
 'aim': 0.0,
 'aimed': 0.0,
 'ain': 0.0,
 'aircraft': 0.0,
 'al': 0.0,
 'alfven': 0,
 'alfvenic': 0,
 'algebra': -0.125,
 'algebraic': 0.0,
 'algebras': -0.125,
 'algorithm': 0.0,
 'algorithmic': 0.0,
 'algorithms': 0.0,
 'aligned': 0.0,
 'allow': 0.0,
 'allowed': 0.0,
 'allowing': 0.0,
 'allows': 0.0,
 'alma': 0,
 'alpha': 0.0,
 'alternative': -0.125,
 'aluminum': 0.0,
 'american': 0.0,
 'amounts': 0.0,
 'amplitude': 0.0,
 'amplitudes': 0.0,
 'analogous': -0.25,
 'analogue': 0.0,
 'analogues': 0.0,
 'analyse': 0.0,
 'analysed': 0.0,
 'analyses': 0.0,
 'analysis': 0.0,
 'analytic': 0.0,
 'analytical': 0.0,
 'analytically': 0.0,
 'analyze': 0.0,
 'ando': 0,
 'angle': 0.0,
 'angles': 0.0,
 'angular': 0.0,
 'angus': 0.375,
 'anisotropic': -0.75,
 'anisotropy': 0.0,
 'annealing': 0.0,
 'annihilation': -0.125,
 'ansatz': 0,
 'answer': 0.0,
 'antenna': 0.0,
 'anti': 0.0,
 'antimatter': 0.0,
 'antiquark': 0.0,
 'antistocks': 0,
 'apparent': 0.625,
 'appear': 0.0,
 'appeared': 0.0,
 'appears': 0.0,
 'appendix': 0.0,
 'applicability': 0.25,
 'applicable': 0.5,
 'application': 0.0,
 'applications': 0.0,
 'applied': 0.0,
 'apply': 0.0,
 'approach': 0.0,
 'approached': 0.0,
 'approaches': 0.0,
 'appropriate': 0.125,
 'approximate': 0.0,
 'approximated': 0.0,
 'approximately': 0.25,
 'approximation': -0.25,
 'approximations': -0.25,
 'ar': 0.0,
 'arbitrarily': 0.375,
 'arbitrary': 0.0,
 'arboricity': 0,
 'arcsec': 0.0,
 'area': 0.0,
 'argue': 0.0,
 'argument': 0.0,
 'arguments': 0.0,
 'arises': 0.0,
 'arising': 0.0,
 'arpes': 0,
 'arrangement': 0.0,
 'array': 0.0,
 'arrived': 0.0,
 'arrives': 0.0,
 'article': 0.0,
 'artificial': 0.0,
 'arxiv': 0,
 'asa': 0,
 'aspects': 0.0,
 'assembled': 0.0,
 'associated': 0.0,
 'assume': -0.375,
 'assumed': -0.375,
 'assumptions': 0.0,
 'ast': 0,
 'astrophysical': 0.0,
 'asymptotic': 0.0,
 'asymptotically': 0.0,
 'asymptotics': 0,
 'athermal': 0,
 'atlas': 0.0,
 'atmosphere': 0.0,
 'atomic': 0.0,
 'atoms': 0.0,
 'attachment': 0.0,
 'attachments': 0.0,
 'attained': 0.0,
 'attention': 0.0,
 'attenuation': -0.125,
 'attraction': 0.0,
 'au': -0.125,
 'author': 0.0,
 'authors': 0.0,
 'automata': 0.0,
 'automatic': 0.0,
 'automorphisms': 0,
 'autonomous': 0.0,
 'auxiliary': 0.0,
 'available': 0.375,
 'average': 0.0,
 'averaging': -0.625,
 'avoided': 0.0,
 'away': 0.0,
 'axis': 0.0,
 'axisymmetric': 0,
 'b_0': 0,
 'babar': 0.0,
 'background': 0.0,
 'backgrounds': 0.0,
 'balls': 0.0,
 'band': 0.0,
 'bar': 0.0,
 'barely': 0.125,
 'bars': 0.0,
 'baryons': 0.0,
 'base': 0.0,
 'based': 0.0,
 'basic': 0.0,
 'basis': 0.0,
 'bcs': 0,
 'beam': -0.25,
 'bec': 0,
 'becchi': 0,
 'becs': 0,
 'begin': 0.0,
 'behavior': 0.25,
 'behaviors': 0.25,
 'behaviour': 0.0,
 'belle': 0.5,
 'benefits': 0.0,
 'bent': 0.125,
 'berwald': 0,
 'beta': 0.0,
 'biawgn': 0,
 'bifurcations': 0.0,
 'big': 0.125,
 'bigger': 0.125,
 'bijection': 0,
 'bilayer': 0,
 'bilinear': 0.125,
 'billion': 0.0,
 'bima': 0,
 'bimodule': 0,
 'bimodules': 0,
 'binaries': 0.0,
 'binary': 0.0,
 'binding': 0.0,
 'bio': 0,
 'biological': 0.0,
 'bipartite': 0.0,
 'bistability': 0,
 'bit': -0.125,
 'black': -0.375,
 'blind': 0.0,
 'blocks': 0.0,
 'blow': 0.0,
 'blows': 0.0,
 'blowup': 0.0,
 'blowups': 0.0,
 'blue': 0.0,
 'blurring': 0.0,
 'bodies': 0.0,
 'body': 0.0,
 'bohm': 0,
 'boiling': 0.0,
 'boltzmann': 0.0,
 'bona': 0,
 'bonding': 0.0,
 'borcherds': 0,
 'bore': -0.125,
 'bores': -0.125,
 'bose': 0.0,
 'boson': 0.0,
 'bosonic': 0,
 'bosons': 0.0,
 'bound': 0.0,
 'boundaries': 0.0,
 'boundary': 0.0,
 'bounded': 0.0,
 'bourin': 0,
 'box': 0.0,
 'br': 0.0,
 'bracket': 0.25,
 'branching': 0.0,
 'brane': 0,
 'breaking': 0.0,
 'breaks': 0.0,
 'brief': 0.0,
 'bright': 0.125,
 'brillouin': 0,
 'brings': 0.0,
 'broad': 0.0,
 'broadening': 0.0,
 'brought': 0.0,
 'brst': 0,
 'bruinier': 0,
 'bss': 0.0,
 'building': 0.0,
 'bulk': 0.0,
 'bullet': 0.0,
 'burago': 0,
 'burst': 0.0,
 'c2d': 0,
 'c_': 0,
 'cabibbo': 0,
 'calculate': 0.0,
 'calculated': 0.0,
 'calculating': 0.0,
 'calculation': 0.0,
 'calculations': 0.0,
 'calibration': 0.125,
 'called': 0.25,
 'callias': 0,
 'cancellations': 0.0,
 'candidate': 0.0,
 'canonical': -0.25,
 'canonically': 0.125,
 'cap': 0.0,
 'capabilities': 0.5,
 'capacity': 0.0,
 'capture': 0.0,
 'captures': 0.0,
 'careful': 0.5,
 'carefully': 0.0,
 'carlo': 0,
 'carlsson': 0,
 'carried': 0.0,
 'cartesian': 0.0,
 'cascade': 0.0,
 'cascades': 0.0,
 'case': 0.0,
 'cases': 0.0,
 'casimir': 0,
 'castell': 0,
 'catalytic': -0.375,
 'category': 0.0,
 'cause': 0.0,
 'caused': 0.0,
 'cavity': 0.0,
 'cayley': 0,
 'cc': 0.0,
 'cdf': 0,
 'cdm': 0,
 'cdma': 0,
 'cdp': 0,
 'cell': 0.0,
 'central': 0.0,
 'certain': -0.375,
 'certifies': 0.0,
 'chain': 0.0,
 'challenges': 0.125,
 'changed': 0.0,
 'changes': 0.0,
 'changing': 0.0,
 'channel': 0.0,
 'channels': 0.0,
 'chaotic': -0.125,
 'characteristics': 0.0,
 'characterization': 0.0,
 'characterizations': 0.0,
 'characterize': -0.25,
 'characters': 0.0,
 'charmed': 0.5,
 'chemical': 0.0,
 'chen': 0.0,
 'cherenkov': 0,
 'chezy': 0,
 'chi': 0.25,
 'chosen': 0.0,
 'chromodynamics': 0,
 'chromosomes': 0.0,
 'chromosphere': 0.0,
 'chromospheric': 0,
 'circular': 0.0,
 'circularized': 0.0,
 'circularly': 0.0,
 'circulating': 0.0,
 'circumstances': 0.0,
 'cite': 0.0,
 'claiming': 0.0,
 'claims': 0.125,
 'clarified': 0.25,
 'clarifies': 0.25,
 'class': 0.0,
 'classes': 0.0,
 'classical': 0.25,
 'classification': 0.0,
 'classified': 0.0,
 'classify': 0.0,
 'clean': 0.0,
 'close': 0.0,
 'closed': 0.0,
 'closest': 0.0,
 'cluster': -0.125,
 'clustered': 0.0,
 'clustering': -0.125,
 'clusters': -0.125,
 'coarse': 0.0,
 'code': 0.0,
 'codes': 0.0,
 'coefficient': 0.0,
 'coefficients': 0.0,
 'coexist': 0.0,
 'cohen': 0,
 'coherence': 0.0,
 'coherent': 0.25,
 'cohomological': 0,
 'cohomology': 0,
 'cold': -0.125,
 'collaboration': 0.0,
 'collide': -0.125,
 'collider': 0.0,
 'colliders': 0.0,
 'collision': 0.0,
 'collisional': 0,
 'collisionless': 0,
 'collisions': 0.0,
 'colocalized': 0,
 'color': 0.0,
 'colored': 0.0,
 'colors': 0.0,
 'columnar': 0.0,
 'combinatorial': 0.0,
 'combinatorics': 0,
 'combine': 0.0,
 'combined': -0.125,
 'commensurable': 0.0,
 'common': 0.0,
 'commonly': 0.0,
 'commutation': 0.0,
 'commutative': 0.0,
 'compact': 0.0,
 'comparable': 0.5,
 'compare': 0.25,
 'compared': -0.125,
 'compares': 0.25,
 'comparing': -0.25,
 'comparison': -0.25,
 'compatibility': 0.0,
 'compete': 0.0,
 'complete': 0.0,
 'complex': 0.0,
 'complexity': 0.25,
 'complicated': -0.125,
 'component': 0.0,
 'components': 0.0,
 'composite': 0.0,
 'compound': 0.0,
 'comprehensive': 0.0,
 'compression': 0.0,
 'compressive': 0,
 'comprised': 0.125,
 'comprises': 0.125,
 'computational': 0.0,
 'computations': 0.0,
 'compute': 0.0,
 'computed': 0.0,
 'computer': 0.0,
 'computers': 0.0,
 'computing': 0.0,
 'concave': 0.0,
 'concentration': 0.0,
 'concentrations': 0.0,
 'concept': 0.0,
 'concerning': 0.0,
 'conclusion': 0.0,
 'conclusions': 0.0,
 'condensate': 0.0,
 'condensates': 0.0,
 'condition': 0.0,
 'conditional': 0.375,
 'conditionally': -0.5,
 'conditions': 0.0,
 'conduction': 0.0,
 'conductivity': 0.0,
 'confidence': 0.0,
 'configurations': 0.0,
 'confinement': 0.0,
 'confirm': 0.0,
 'confirmed': 0.0,
 'confirming': 0.0,
 'confirms': 0.0,
 'conformal': 0,
 'congruences': 0.625,
 'conjecture': 0.0,
 'conjugacy': 0,
 'conjugate': 0.0,
 'connected': 0.0,
 'connecting': 0.0,
 'connections': -0.125,
 'consensus': 0.0,
 'consequence': 0.0,
 'consequences': 0.0,
 'conservation': -0.25,
 'consider': 0.125,
 'consideration': 0.25,
 'considered': 0.125,
 'considering': 0.125,
 'considers': 0.125,
 'consistency': 0.0,
 'consistent': 0.25,
 'consisting': 0.0,
 'consists': 0.0,
 'constant': -0.25,
 'constituent': 0.0,
 'constraining': 0.0,
 'constrains': 0.0,
 'constraint': 0.0,
 'constraints': 0.0,
 'construct': 0.0,
 'constructed': 0.0,
 'construction': 0.0,
 'constructions': 0.0,
 'contact': 0.375,
 'containing': 0.0,
 'contains': 0.0,
 'contamination': 0.0,
 'context': 0.0,
 'contexts': 0.0,
 'continuation': 0.0,
 'continue': 0.0,
 'continuity': 0.0,
 'continuous': 0.0,
 'continuum': -0.25,
 'contraction': 0.0,
 'contradict': 0.0,
 'contrasted': 0.125,
 'contribution': 0.0,
 'contributions': 0.0,
 'control': 0.0,
 'controlled': 0.0,
 'conventional': 0.0,
 'converge': 0.0,
 'convergence': 0.0,
 'conversion': 0.0,
 'conversions': 0.0,
 'converted': 0.0,
 'convex': 0.0,
 'cool': -0.125,
 'cooling': 0.0,
 'cooper': 0.0,
 'coordinate': 0.0,
 'coordinates': 0.0,
 'corollary': 0.125,
 'corotation': 0,
 'correct': 0.25,
 'correction': 0.0,
 'correlated': 0.0,
 'correlation': 0.0,
 'correlations': 0.0,
 'correspond': 0.375,
 'correspondence': 0.0,
 'corresponding': 0.375,
 'corresponds': 0.375,
 'cosine': 0.0,
 'cosmological': 0.0,
 'cosmologies': 0.25,
 'cosmology': 0.25,
 'cost': 0.0,
 'costs': 0.0,
 'coulomb': 0.0,
 'countable': 0.0,
 'counterpart': 0.0,
 'counterparts': 0.0,
 'counts': 0.0,
 'coupled': 0.0,
 'coupling': 0.0,
 'couplings': 0.0,
 'course': 0.0,
 'covariant': -0.375,
 'covered': 0.0,
 'covering': 0.0,
 'cp': 0,
 'create': 0.0,
 'creation': 0.0,
 'criteria': 0.0,
 'criterion': 0.0,
 'critical': -0.5,
 'cross': 0.0,
 'crossover': 0.0,
 'crystal': 0.0,
 'csft': 0,
 'cu': 0.0,
 'cubes': 0.0,
 'cubically': 0,
 'cuprate': 0,
 'current': 0.0,
 'currents': 0.0,
 'curtain': 0.0,
 'curtains': 0.0,
 'curvature': 0.0,
 'curve': 0.0,
 'cusp': 0.0,
 'cycle': 0.0,
 'cycles': 0.0,
 'cyclic': 0.5,
 'cyclotron': 0.0,
 'd0': 0,
 'damped': 0.0,
 'dark': -0.375,
 'data': 0.0,
 'datum': 0.0,
 'days': 0.0,
 'dda': 0,
 'deal': 0.0,
 'debris': -0.375,
 'decay': -0.375,
 'decays': -0.375,
 'decode': 0.0,
 'decoding': 0.125,
 'decomposable': 0.625,
 'decomposition': 0.0,
 'decompositions': 0.0,
 'decompression': 0.0,
 'decrease': 0.0,
 'decreases': 0.0,
 'deduced': 0.0,
 'deep': 0.0,
 'defects': 0.0,
 'define': 0.375,
 'defined': 0.375,
 'definite': 0.75,
 'definition': 0.0,
 'definitions': 0.0,
 'deformation': -0.25,
 'deformations': -0.25,
 'deg': 0,
 'delay': 0.0,
 'deleptonised': 0,
 'demonstrate': 0.0,
 'demonstrated': 0.0,
 'denotes': 0.0,
 'dense': 0.0,
 'densities': 0.0,
 'density': 0.0,
 'depend': 0.0,
 'dependence': 0.0,
 'dependent': 0.0,
 'depending': 0.0,
 'depends': 0.0,
 'dephosphorylation': 0,
 'der': 0.0,
 'derham': 0,
 'derivatives': 0.0,
 'derive': 0.0,
 'derived': 0.0,
 'described': 0.0,
 'describes': 0.0,
 'describing': 0.0,
 'description': 0.0,
 'desingularizations': 0,
 'destructive': -0.625,
 'detailed': 0.0,
 'details': 0.0,
 'detect': 0.0,
 'detectability': 0,
 'detected': 0.0,
 'detecting': 0.0,
 'detection': 0.0,
 'detector': 0.0,
 'determinant': 0.0,
 'determinants': 0.0,
 'determination': 0.0,
 'determinations': 0.0,
 'determine': 0.0,
 'determined': 0.0,
 'deterministic': -0.375,
 'develop': 0.0,
 'developed': 0.0,
 'developing': 0.0,
 'development': 0.0,
 'developments': 0.0,
 'develops': 0.0,
 'devices': 0.0,
 'devised': 0.0,
 'df': 0,
 'dft': 0,
 'diagonal': 0.0,
 'diagram': 0.125,
 'diagrammatic': 0.0,
 'diagrams': 0.125,
 'dickson': 0,
 'die': 0.0,
 'difference': -0.375,
 'differences': -0.375,
 'different': 0.625,
 'differential': 0.0,
 'difficult': -0.75,
 'diffractively': 0,
 'diffusion': 0.0,
 'dilaton': 0,
 'dilute': -0.125,
 'dimension': 0.0,
 'dimensional': 0.0,
 'dimensions': 0.0,
 'dinger': 0,
 'diosi': 0,
 'diphoton': 0,
 'dipolar': 0.0,
 'dipole': 0.0,
 'dipoles': 0.0,
 'diquark': 0,
 'direct': 0.0,
 'directly': 0.0,
 'disc': 0.0,
 'discontinuity': -0.125,
 'discontinuous': 0.0,
 'discovered': 0.0,
 'discrepancy': -0.125,
 'discrete': 0.0,
 'discretization': 0,
 'discretizations': 0,
 'discuss': 0.0,
 'discussed': 0.0,
 'discusses': 0.0,
 'discussion': 0.0,
 'discussions': 0.0,
 'disk': 0.0,
 'disks': 0.0,
 'dispersive': -0.125,
 'disribution': 0,
 'disruption': 0.0,
 'dissipation': 0.0,
 'distance': 0.0,
 'distinct': 0.25,
 'distinctive': 0.0,
 'distinguish': -0.25,
 'distinguished': -0.25,
 'distinguishing': -0.25,
 'distortion': -0.25,
 'distortions': -0.25,
 'distributed': 0.0,
 'distribution': 0.25,
 'distributions': 0.25,
 'diverge': 0.0,
 'divergence': 0.0,
 'division': 0.0,
 'divisors': 0.0,
 'djokovi': 0,
 'dm': -0.625,
 'dmft': 0,
 'dna': 0.0,
 'dobzhanski': 0,
 'does': 0.0,
 'domain': 0.0,
 'dominated': 0.0,
 'doping': 0.125,
 'doppler': 0.0,
 'dot': 0.125,
 'dots': 0.125,
 'double': 0.0,
 'doubly': 0.0,
 'downstream': 0.0,
 'dramatic': 0.5,
 'drive': 0.0,
 'driven': 0.0,
 'dt': 0,
 'dual': 0.0,
 'duration': 0.0,
 'durations': 0.0,
 'dw': 0,
 'dwarf': 0.0,
 'dyadic': 0.0,
 'dynamic': 0.5,
 'dynamical': 0.125,
 'dynamically': 0.25,
 'dynamics': 0.0,
 'e1': 0,
 'e2': 0,
 'e_': 0,
 'e_1': 0,
 'e_g': 0,
 'e_i': 0,
 'e_k': 0,
 'e_n': 0,
 'earlier': 0.0,
 'early': 0.0,
 'earth': 0.0,
 'easily': 0.25,
 'eclipses': 0.0,
 'eclipsing': 0.0,
 'edge': 0.0,
 'edges': 0.0,
 'effect': 0.0,
 'effective': 0.125,
 'effects': -0.125,
 'efficiency': 0.0,
 'efforts': 0.0,
 'eigenforms': 0,
 'eigensystems': 0,
 'einstein': 0.0,
 'eisentein': 0,
 'elastic': 0.0,
 'electric': 0.0,
 'electron': 0.0,
 'electronic': 0.0,
 'electrons': 0.0,
 'elementary': -0.25,
 'elements': -0.375,
 'ell': 0.0,
 'ellipsoidal': 0.0,
 'em': 0.0,
 'embeddings': 0,
 'emerging': 0.0,
 'emission': 0.0,
 'emit': 0.0,
 'emmiting': 0,
 'emphasis': 0.75,
 'empirically': 0.375,
 'employ': 0.0,
 'employed': 0.0,
 'enable': 0.375,
 'enables': 0.375,
 'end': 0.0,
 'energetical': 0,
 'energies': 0.0,
 'energy': 0.0,
 'enhanced': 0.0,
 'enhancement': 0.375,
 'enjoy': 0.375,
 'ensemble': 0.0,
 'ensuring': 0.0,
 'entail': 0.0,
 'entirely': 0.5,
 'entropic': 0,
 'entropy': 0.0,
 'envelope': 0.0,
 'enzyme': 0.0,
 'enzymes': 0.0,
 'enzymic': 0,
 'epitaxial': 0,
 'epsilon': 0.0,
 'equalities': -0.5,
 'equation': 0.0,
 'equations': 0.0,
 'equilibrium': 0.0,
 'equivalences': 0.0,
 'equivalent': 0.0,
 'equivariant': 0,
 'erase': 0.0,
 'ergodic': 0.0,
 'erosion': 0.0,
 'error': -0.625,
 'errors': -0.625,
 'es': 0.0,
 'especially': 0.0,
 'essential': -0.125,
 'essentially': 0.5,
 'establish': 0.0,
 'established': 0.0,
 'estimate': -0.25,
 'estimated': 0.0,
 'estimates': -0.25,
 'estimation': 0.0,
 'estimator': 0.0,
 'esz': 0,
 'et': 0,
 'euclidean': 0.0,
 'ev': 0.0,
 'evaluate': 0.0,
 'evaluated': 0.0,
 'evaluation': 0.125,
 'evaporation': 0.0,
 'event': 0.0,
 'events': 0.0,
 'evidence': 0.0,
 'evidences': 0.0,
 'evolution': 0.0,
 'evolved': 0.0,
 'evolves': 0.0,
 'evolving': 0.0,
 'ex': 0.0,
 'exact': 0.0,
 'exactly': 0.125,
 'examine': 0.0,
 'examined': 0.0,
 'example': 0.0,
 'examples': 0.0,
 'exceedingly': -0.125,
 'excellent': 1.0,
 'excess': 0.125,
 'exchange': 0.0,
 'excitation': 0.125,
 'excited': -0.125,
 'exciton': 0,
 'exhibit': 0.0,
 'exhibits': 0.0,
 'existed': 0.0,
 'existence': 0.0,
 'existing': 0.0,
 'exists': 0.0,
 'expanded': 0.0,
 'expanding': 0.0,
 'expansion': 0.0,
 'expectations': 0.0,
 'expected': 0.0,
 'experiment': 0.0,
 'experimental': 0.0,
 'experimentally': 0.0,
 'experiments': 0.0,
 'explained': 0.25,
 'explaining': 0.25,
 'explicit': 0.5,
 'explore': 0.0,
 'explored': 0.0,
 'explores': 0.0,
 'exponential': 0.0,
 'exponents': 0.0,
 'exposes': 0.125,
 'exposition': 0.0,
 'expressed': 0.0,
 'expression': 0.0,
 'extend': 0.0,
 'extending': 0.0,
 'extends': 0.0,
 'extensive': 0.0,
 'exterior': 0.0,
 'external': 0.0,
 'extinction': -0.5,
 'extra': 0.0,
 'extracted': 0.0,
 'extraordinary': 0.625,
 'extrapolation': 0.0,
 'extremely': 0.625,
 'f7v': 0,
 'f_1': 0,
 'f_j': 0,
 'f_l': 0,
 'f_m': 0,
 'fabo': 0,
 'facilities': 0.0,
 'fact': 0.0,
 'factor': 0.0,
 'factorial': 0.0,
 ...}

#### Lo que hace la siguiente función es que toma el abstract de cada articulo lo separa por palabra con '.split()' y lo compara con su valor sentimental en el diccionario de sentimientos para calcular el sentimiento general del abstract/articulo

In [29]:
def calcular_sentimiento_general(texto, diccionario):
    palabras = texto.split()
    if not palabras: 
        return 0
    
    # BUSCAMOS LA PALABRA EN EL DICCIONARIO DE SENTIMIENTOS, Y SI NO LA ENCONTRAMOS, DEVOLVEMOS 0. ASI, SI UNA PALABRA NO TIENE UN SENTIMIENTO ASOCIADO, NO AFECTA EL CALCULO DEL SENTIMIENTO GENERAL DEL TEXTO.
    # .get(palabra, 0) DEVUELVE 0 SI LA PALABRA NO ESTA EN EL DICCIONARIO
    puntajes = [diccionario.get(p.lower(), 0) for p in palabras]
    
    return sum(puntajes) / len(palabras)

In [30]:
#Sentiwordnet es un tipo diccionario que asigna emociones a ciertas palabras, existen mas diccionarios de este tipo,
#WordNet, que se va más al significado y sinonimos
df_datos['sentimiento_neto'] = df_datos['abstract'].apply(
    lambda x: calcular_sentimiento_general(x, sentimientos)
)

In [32]:
df_datos.head(100) # MOSTRAMOS LAS PRIMERAS FILAS DEL DATAFRAME PARA VER LA NUEVA COLUMNA DE SENTIMIENTO NETO

,abstract,year,category,sentimiento_neto
0,A fully differential calculation in perturba...,2008,hep-ph,0.015179
1,"We describe a new algorithm, the $(k,\ell)$-...",2008,math.CO,-0.002174
2,The evolution of Earth-Moon system is descri...,2008,physics.gen-ph,-0.007812
3,We show that a determinant of Stirling cycle...,2007,math.CO,-0.014286
4,In this paper we show how to compute the $\L...,2013,math.CA,0.000000
...,...,...,...,...
95,In this note we present three representation...,2007,nlin.SI,-0.001984
96,We review recent progress in operator algebr...,2007,math-ph,0.031250
97,"Sparse Code Division Multiple Access (CDMA),...",2009,cs.IT,-0.017045
98,For positive semidefinite matrices $A$ and $...,2007,math.FA,-0.013441
99,The topological structure of the event horiz...,2008,gr-qc,-0.017578